export const mockServices = [
  { id: 1, name: "Dọn phòng hàng ngày" },
  { id: 2, name: "Giặt ủi" },
  { id: 3, name: "Đưa đón sân bay" },
  { id: 4, name: "Bữa sáng tự chọn" },
  { id: 5, name: "Thuê xe máy" },
  { id: 6, name: "Thuê xe đạp" },
  { id: 7, name: "Tour du lịch" },
  { id: 8, name: "Massage" },
  { id: 9, name: "Nấu ăn theo yêu cầu" },
  { id: 10, name: "Trông trẻ" },
  { id: 11, name: "BBQ ngoài trời" },
  { id: 12, name: "Karaoke" },
  { id: 13, name: "Tổ chức sự kiện" },
  { id: 14, name: "Cho thuê phòng họp" },
  { id: 15, name: "Hướng dẫn viên du lịch" },
  { id: 16, name: "Dịch vụ spa" },
  { id: 17, name: "Cho thuê xe hơi" },
  { id: 18, name: "Đặt vé tham quan" },
  { id: 19, name: "Phục vụ ăn tại phòng" },
  { id: 20, name: "Gửi hành lý" },
];
